# data setting
stroke_length: 150
test_path: /home/jefflin/dataset/test_all
target_path: /home/jefflin/dataset/target
batch_size: 128
num_workers: 8

# model setting
model_name: ADBPN # FSRCNN, DDBPN, DBPN
scale: 1

gpu_id: 0
# load can be define by bool or path
load: True # load exist .pickle file or not
# load: ./path # load by path
model_args: # model args, for more detail, please take a look in model/model name/models.py
  stages: 2
  n0: 64
  nr: 18
  atten: col

# scheduler
# scheduler can be defined by name or bool
scheduler: step # define by name
# scheduler: true # define by bool
step: 5
factor: 0.9

# weighted loss
alpha: 1 # mse loss weight
beta: 1 # content loss weight
criterion: huber

# logger setting
log_path: ./logs

# output setting
save_path: ./output
